-- Compliance Certification Center §8.8 — verification source config table + seed.

CREATE TABLE IF NOT EXISTS plenum_cafm.compliance_verification_sources
(
    certificate_type_code  varchar(80)  NOT NULL,
    cert_scope             varchar(20)  NOT NULL,
    verification_group     varchar(40)  NOT NULL,
    channel                varchar(20)  NOT NULL,
    register               varchar(120),
    source_url             text,
    api_available          varchar(12)  NOT NULL,
    refresh_cadence        varchar(20),
    notes                  text,
    code_aliases           jsonb        NOT NULL DEFAULT '[]'::jsonb,
    country_code           varchar(8)   NOT NULL DEFAULT 'UK',
    created_at             timestamptz  NOT NULL DEFAULT now(),
    updated_at             timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT compliance_verification_sources_pkey
        PRIMARY KEY (certificate_type_code, country_code)
);

INSERT INTO plenum_cafm.compliance_verification_sources
    (certificate_type_code, cert_scope, verification_group, channel, register, source_url, api_available, refresh_cadence, notes, code_aliases)
VALUES
('FRA',               'building','Fire protection','website',      'Assessor body (IFSM/IFE/FPA/BAFE SP205)', NULL,                                                                       'no',     '90d',  'No central register; verify assessor membership manually', '[]'::jsonb),
('FIRE_ALARM_SVC',    'building','Fire protection','website',      'BAFE',        'https://bafe.my.salesforce-sites.com/wb/wbCompanyVerify',                                                    'no',     '90d',  NULL, '["FIRE_ALARM_SERVICE"]'::jsonb),
('EMERGENCY_LIGHTING','building','Electrical',     'private_api',  'NICEIC/NAPIT','https://www.niceic.com/find-a-contractor',                                                  'partner','90d',  NULL, '[]'::jsonb),
('SPRINKLER_TEST',    'building','Fire protection','website',      'BAFE SP101',  'https://bafe.my.salesforce-sites.com/wb/wbCompanyVerify',                                                    'no',     '90d',  NULL, '["SPRINKLER"]'::jsonb),
('FIRE_DOOR',         'building','Fire protection','website',      'FDIS/BWF-CERTIFIRE','https://www.fdis.org.uk/',                                                            'no',     '90d',  NULL, '[]'::jsonb),
('EICR',              'building','Electrical',     'private_api',  'NICEIC/NAPIT','https://www.niceic.com/find-a-contractor',                                                  'partner','90d',  NULL, '[]'::jsonb),
('EIC',               'building','Electrical',     'private_api',  'NICEIC/NAPIT','https://www.niceic.com/find-a-contractor',                                                  'partner','90d',  NULL, '[]'::jsonb),
('PAT',               'building','Electrical',     'self_produced','Self-held',   NULL,                                                                                        'n/a',    'n/a',  'Register is self-held; no external check', '[]'::jsonb),
('GAS_CP17',          'building','Gas',            'private_api',  'Gas Safe Register','https://www.gassaferegister.co.uk/find-an-engineer/',                     'partner','90d',  NULL, '["CP17","GAS_SAFE_CP17"]'::jsonb),
('BOILER_SVC',        'building','Gas',            'private_api',  'Gas Safe Register','https://www.gassaferegister.co.uk/find-an-engineer/',                     'partner','90d',  NULL, '["BOILER_SERVICE"]'::jsonb),
('LEGIONELLA_RA',     'building','Water / Legionella','website',   'LCA',         'https://www.legionellacontrol.org.uk/members/',                                          'no',     '90d',  NULL, '["L8_RISK","LEGIONELLA"]'::jsonb),
('LEGIONELLA_LOG',    'building','Water / Legionella','self_produced','Self-held',NULL,                                                                                        'n/a',    'n/a',  'Monitoring log; no external register', '[]'::jsonb),
('CWST_INSPECTION',   'building','Water / Legionella','website',   'LCA',         'https://www.legionellacontrol.org.uk/members/',                                          'no',     '90d',  NULL, '["COLD_WATER_TANK"]'::jsonb),
('WSE_PRESSURE',      'building','Lifts',          'website',      'Insurance inspection body','https://www.hse.gov.uk/pressure-systems/written-scheme.htm',                    'no',     '90d',  'Competent person via insurer; no register', '[]'::jsonb),
('LOLER_LIFT',        'building','Lifts',          'website',      'HSE competent-persons','https://www.hse.gov.uk/work-equipment-machinery/thorough-examinations-lifting-equipment.htm','no','90d',NULL, '["LOLER"]'::jsonb),
('ASBESTOS_SURVEY',   'building','Asbestos',       'data_dump',    'UKAS',        'https://www.ukas.com/find-an-organisation/',                                                 'no',     'weekly','Bulk directory ingest', '["UKAS_ASBESTOS"]'::jsonb),
('ASBESTOS_REGISTER', 'building','Asbestos',       'self_produced','Self-held',   NULL,                                                                                        'n/a',    'n/a',  'Living document', '[]'::jsonb),
('EPC',               'building','Energy',         'public_api',   'GOV.UK Find Energy Certificate','https://find-energy-certificate.service.gov.uk/find-a-certificate/search-by-reference-number', 'yes',    '90d',  'Open API', '[]'::jsonb),
('TM44',              'building','Energy',         'public_api',   'GOV.UK Find Energy Certificate','https://find-energy-certificate.service.gov.uk/find-a-certificate/search-by-reference-number', 'yes',    '90d',  'AC inspection lodged on EPC register', '[]'::jsonb),
('DEC',               'building','Energy',         'public_api',   'GOV.UK Find Energy Certificate','https://find-energy-certificate.service.gov.uk/find-a-certificate/search-by-reference-number', 'yes','90d','Open API', '[]'::jsonb),
('ESOS',              'building','Energy',         'public_api',   'Companies House / Environment Agency','https://find-and-update.company-information.service.gov.uk/',        'yes',    '90d',  'Company check via CH API; EA notification website', '[]'::jsonb),
('FGAS_LEAK',         'building','F-Gas',          'website',      'REFCOM',      'https://www.refcom.org.uk/find-a-company/',                                                          'no',     '90d',  NULL, '["FGAS"]'::jsonb),
('HS_POLICY',         'building','—',              'self_produced','Self-held',   NULL,                                                                                        'n/a',    'n/a',  'Policy statement', '[]'::jsonb),
('RISK_REGISTER',     'building','—',              'self_produced','Self-held',   NULL,                                                                                        'n/a',    'n/a',  'Risk assessment register', '[]'::jsonb),
('EL_INSURANCE',      'building','Insurance',      'public_api',   'FCA Register','https://register.fca.org.uk/',                                                              'yes',    '90d',  'Insurer authorisation via FCA API', '[]'::jsonb),
('HRB_REGISTRATION',  'building','Building safety','website',      'Building Safety Regulator','https://www.hse.gov.uk/building-safety/registration.htm',                       'no',     '90d',  NULL, '[]'::jsonb),
('SAFETY_CASE',       'building','Building safety','website',      'Building Safety Regulator','https://www.hse.gov.uk/building-safety/registration.htm',                        'no',     '90d',  NULL, '[]'::jsonb),
('GASSAFE_COMPANY',   'vendor','Gas',              'private_api',  'Gas Safe Register','https://www.gassaferegister.co.uk/find-an-engineer/',                     'partner','90d',  NULL, '["GAS_SAFE"]'::jsonb),
('ACS_GAS_CARD',      'vendor','Gas',              'private_api',  'Gas Safe Register','https://www.gassaferegister.co.uk/find-an-engineer/',                     'partner','90d',  'Individual engineer card check', '["ACS_CARD"]'::jsonb),
('NICEIC_CONTRACTOR', 'vendor','Electrical',       'private_api',  'NICEIC',      'https://www.niceic.com/find-a-contractor',                                                  'partner','90d',  NULL, '["NICEIC"]'::jsonb),
('NAPIT_REG',         'vendor','Electrical',       'private_api',  'NAPIT',       'https://www.napit.org.uk/find-an-installer',                                                'partner','90d',  NULL, '["NAPIT"]'::jsonb),
('CG_2382',           'vendor','Electrical',       'cert_format',  'City & Guilds','https://www.cityandguilds.com/', 'no','n/a','Qualification; no live register', '[]'::jsonb),
('BAFE_SP203',        'vendor','Fire protection',  'website',      'BAFE',        'https://bafe.my.salesforce-sites.com/wb/wbCompanyVerify',                                                    'no',     '90d',  NULL, '["BAFE","BAFE_SP203_1"]'::jsonb),
('NSI_GOLD_FIRE',     'vendor','Fire protection',  'website',      'NSI',         'https://www.nsi.org.uk/find-a-company/',                                               'no',     '90d',  NULL, '["NSI"]'::jsonb),
('BAFE_SP101',        'vendor','Fire protection',  'website',      'BAFE',        'https://bafe.my.salesforce-sites.com/wb/wbCompanyVerify',                                                    'no',     '90d',  NULL, '[]'::jsonb),
('BAFE_SP105',        'vendor','Fire protection',  'website',      'BAFE',        'https://bafe.my.salesforce-sites.com/wb/wbCompanyVerify',                                                    'no',     '90d',  NULL, '[]'::jsonb),
('LEIA_MEMBER',       'vendor','Lifts',            'website',      'LEIA',        'https://www.leia.co.uk/',                                                'no',     '90d',  NULL, '["LEIA"]'::jsonb),
('LOLER_CP',          'vendor','Lifts',            'website',      'HSE competent-persons','https://www.hse.gov.uk/work-equipment-machinery/thorough-examinations-lifting-equipment.htm','no','90d',NULL, '[]'::jsonb),
('ASBESTOS_LICENCE',  'vendor','Asbestos',         'data_dump',    'HSE licensed contractors','https://www.ukata.org.uk/library/hse-licensed-asbestos-removal-contractors-register/', 'no',     'weekly','Full HSE licensed-contractor list + searchable LARC finder (via UKATA)', '["HSE_ASBESTOS_LICENCE"]'::jsonb),
('UKAS_ASBESTOS',     'vendor','Asbestos',         'data_dump',    'UKAS',        'https://www.ukas.com/find-an-organisation/',                                                 'no',     'weekly','Bulk directory ingest', '[]'::jsonb),
('BOHS_P40x',         'vendor','Asbestos',         'cert_format',  'BOHS/RSPH',   'https://www.bohs.org/learning/qualifications/p400-series/',                                  'no',     'n/a',  'Individual competency; no live register', '["P402","P403","P404"]'::jsonb),
('LCA_REG',           'vendor','Water / Legionella','website',     'LCA',         'https://www.legionellacontrol.org.uk/members/',                                          'no',     '90d',  NULL, '["LCA"]'::jsonb),
('LEGIONELLA_COMP',   'vendor','Water / Legionella','cert_format', 'BOHS/WMSoc',  'https://www.wmsoc.org.uk/',                                                                  'no',     'n/a',  'Individual competency', '[]'::jsonb),
('REFCOM_COMPANY',    'vendor','F-Gas',            'website',      'REFCOM',      'https://www.refcom.org.uk/find-a-company/',                                                          'no',     '90d',  NULL, '["REFCOM"]'::jsonb),
('CG_2079',           'vendor','F-Gas',            'website',      'REFCOM (technician)','https://www.refcom.org.uk/find-a-company/',                                                   'no',     '90d',  'Individual technician checkable via REFCOM', '[]'::jsonb),
('CHAS_SSIP',         'vendor','General / SSIP',   'private_api',  'SSIP / CHAS', 'https://ssip.org.uk/members/',                                                         'partner','90d',  NULL, '["CHAS","SSIP","CHAS_SSIP"]'::jsonb),
('ISO_9001',          'vendor','General / SSIP',   'website',      'UKAS CertCheck (live)','https://certcheck.ukas.com/',                                                     'no',     'weekly','Live UKAS CertCheck DB — search by cert number or company', '[]'::jsonb),
('ISO_14001',         'vendor','General / SSIP',   'website',      'UKAS CertCheck (live)','https://certcheck.ukas.com/',                                                     'no',     'weekly','Live UKAS CertCheck DB — search by cert number or company', '[]'::jsonb),
('CONTRACTOR_EL',     'vendor','Insurance',        'public_api',   'FCA Register','https://register.fca.org.uk/',                                                              'yes',    '90d',  'Insurer authorisation via FCA API', '["CONTRACTOR_EL_INSURANCE"]'::jsonb),
('CONTRACTOR_PL',     'vendor','Insurance',        'public_api',   'FCA Register','https://register.fca.org.uk/',                                                              'yes',    '90d',  'Insurer authorisation via FCA API', '["CONTRACTOR_PL_INSURANCE"]'::jsonb),
('SIA_ACS',           'vendor','Security',         'data_dump',    'SIA ACS register','https://www.services.sia.homeoffice.gov.uk/Pages/acs-roac.aspx?all',                        'no',     'weekly','Register of Approved Contractors — full list (Ctrl+F by company)', '[]'::jsonb),
('SIA_LICENCE',       'vendor','Security',         'website',      'SIA licence check','https://www.sia.homeoffice.gov.uk/Pages/licensing-check.aspx',                                'no',     '90d',  'Per-record individual check', '["SIA","SIA_INDIVIDUAL"]'::jsonb),
('NSI_GOLD_SEC',      'vendor','Security',         'website',      'NSI',         'https://www.nsi.org.uk/find-a-company/',                                               'no',     '90d',  NULL, '[]'::jsonb),
('BPCA_MEMBER',       'vendor','Pest control',     'data_dump',    'BPCA',        'https://bpca.org.uk/find-a-pest-controller/',                                                'no',     'weekly','Published member list ingest', '["BPCA"]'::jsonb),
('PESTICIDE_PAx',     'vendor','Pest control',     'data_dump',    'BASIS PROMPT','https://www.basis-reg.co.uk/register/prompt',                                                'no',     'weekly','PROMPT register ingest', '["PA1","PA2","PA6"]'::jsonb)
ON CONFLICT (certificate_type_code, country_code) DO UPDATE SET
    cert_scope = EXCLUDED.cert_scope,
    verification_group = EXCLUDED.verification_group,
    channel = EXCLUDED.channel,
    register = EXCLUDED.register,
    source_url = EXCLUDED.source_url,
    api_available = EXCLUDED.api_available,
    refresh_cadence = EXCLUDED.refresh_cadence,
    notes = EXCLUDED.notes,
    code_aliases = EXCLUDED.code_aliases,
    updated_at = now();
