-- CCC: bootstrap compliance entity tables (vendors/sites/assets) when a tenant schema
-- has none — auto-created on compliance ingest. CREATE TABLE IF NOT EXISTS is a no-op
-- when the base plenum_cafm schema already has them. Generated from the live schema.
CREATE SCHEMA IF NOT EXISTS plenum_cafm;

CREATE TABLE IF NOT EXISTS plenum_cafm.vendors (
    "id" varchar(50) PRIMARY KEY NOT NULL,
    "organization_id" integer,
    "vendor_name" varchar(200),
    "vendor_code" varchar(50),
    "address" text,
    "city" varchar(100),
    "specialty" varchar(100),
    "postal_code" varchar(20),
    "country" varchar(100),
    "phone" varchar(50),
    "fax" varchar(50),
    "website" varchar(200),
    "email" varchar(200),
    "notes" text,
    "status" varchar(50) DEFAULT 'active'::character varying,
    "created_at" timestamp DEFAULT now(),
    "country_id" integer,
    "business_group_id" integer,
    "classification_id" integer,
    "trade" varchar(255),
    "sla_response_mins" varchar(255),
    "employment_type" varchar(255),
    "floors" numeric,
    "level" varchar(255),
    "primary_skill" varchar(255),
    "shift" varchar(255),
    "tech_name" varchar(255),
    "site_id" integer,
    "tech_id" integer,
    "rate_card_hourly_aed" varchar(255),
    "block_state" varchar(20) DEFAULT 'Clear'::character varying,
    "block_reason" text,
    "block_date" timestamptz,
    "blocked_accreditation_type" varchar(255)
);

CREATE TABLE IF NOT EXISTS plenum_cafm.sites (
    "site_id" varchar(50) PRIMARY KEY NOT NULL,
    "organization_id" integer,
    "site_name" varchar(200) NOT NULL,
    "site_code" varchar(50),
    "city" varchar(100),
    "country" varchar(100),
    "timezone" varchar(50) DEFAULT 'Asia/Dubai'::character varying,
    "status" varchar(50) DEFAULT 'active'::character varying,
    "created_at" timestamp DEFAULT now(),
    "site_type" text,
    "floors" text,
    "gfa_sqm" text,
    "occupancy_profile" text,
    "id" text,
    "completed_at" text,
    "handover_date" text,
    "postcode" text,
    "name" text,
    "asset_id" text,
    "manager" text,
    "region" text,
    "manager_email" text
);

CREATE TABLE IF NOT EXISTS plenum_cafm.assets (
    "id" varchar(50) PRIMARY KEY NOT NULL,
    "organization_id" integer,
    "site_id" varchar(50),
    "location_id" integer,
    "category_id" integer,
    "asset_name" varchar(200),
    "asset_code" varchar(100),
    "serial_number" varchar(100),
    "barcode" varchar(100),
    "qr_code" varchar(100),
    "manufacturer" varchar(100),
    "model" varchar(100),
    "model_number" varchar(100),
    "make" varchar(100),
    "installation_date" date,
    "warranty_expiry" date,
    "status" varchar(50) DEFAULT 'active'::character varying,
    "health_score" integer DEFAULT 100,
    "criticality" varchar(20) DEFAULT 'medium'::character varying,
    "is_online" boolean DEFAULT true,
    "location" varchar(200),
    "location_code" varchar(100),
    "parent_asset_id" varchar(50),
    "is_site" boolean DEFAULT false,
    "notes" text,
    "raw_metadata" jsonb,
    "external_asset_id" varchar(100),
    "inventory_code" varchar(100),
    "aisle" varchar(20),
    "row" varchar(20),
    "bin_number" varchar(20),
    "stock_location" varchar(200),
    "charge_department_id" integer,
    "project_id" integer,
    "account_code" varchar(50),
    "account_id" integer,
    "category" varchar(100),
    "created_at" timestamp DEFAULT now(),
    "updated_at" timestamp DEFAULT now(),
    "timezone" varchar(50),
    "country_id" integer,
    "asset_type" varchar(255),
    "document_ids" jsonb DEFAULT '[]'::jsonb,
    "property_ref" varchar(255),
    "condition_score" integer,
    "condition_provenance" jsonb DEFAULT '{}'::jsonb,
    "condition_updated_at" timestamptz
);
