[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:connector]
command=uvicorn cafm_connector.api.app:app --host 127.0.0.1 --port 8000 --root-path /connector
directory=/build/cafm-connector-service
autostart=true
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:ingestion]
command=uvicorn app:app --host 127.0.0.1 --port 8001 --root-path /ingestion
directory=/build/svc-ingestion/src
autostart=true
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:query]
command=uvicorn app:app --host 127.0.0.1 --port 8002 --root-path /query
directory=/build/svc-query/src
autostart=true
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:schema-mapper]
command=uvicorn src.app:app --host 127.0.0.1 --port 8003 --root-path /schema-mapper
directory=/build/svc-ai-schema-mapper
environment=DEBUG="true"
autostart=true
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:doc-rag]
command=uvicorn app.main:app --host 127.0.0.1 --port 8004 --root-path /doc-rag
directory=/build/doc-rag-main
autostart=true
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:work-order]
command=uvicorn src.app:app --host 127.0.0.1 --port 8007 --root-path /work-order
directory=/build/svc-work-order-management
autostart=true
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
