"""Export cleaned tables to runnable SQL INSERT statements (literal values).

Generates INSERT statements in FK-dependency order to avoid constraint violations.
Artifacts are for download/review — not asyncpg prepared-statement execution.
"""

import json
import logging
import re
from datetime import date, datetime
from decimal import Decimal
from typing import Any, Dict, List
from uuid import UUID

from cafm_shared.logging import get_logger

logger = get_logger(__name__)

_SAFE_IDENT = re.compile(r"^[a-z_][a-z0-9_]*$", re.IGNORECASE)


def export_to_sql(
    cleaned_tables: Dict[str, List[Dict]],
    confirmed_hierarchies: List[Dict],
    schema_name: str = "plenum_cafm",
) -> str:
    """
    Export cleaned tables to SQL INSERT statements with literal values.

    Args:
        cleaned_tables: dict[table_name] = [row_dicts]
        confirmed_hierarchies: List of confirmed FK relationships
        schema_name: Target schema name

    Returns:
        SQL script as string (runnable in psql / pgAdmin)
    """

    logger.info("[SQL Exporter] Starting SQL INSERT generation...")

    insertion_order = _determine_insertion_order(
        list(cleaned_tables.keys()),
        confirmed_hierarchies,
    )

    logger.info(f"[SQL Exporter] Insertion order: {' > '.join(insertion_order)}")

    sql_lines = [
        "-- Auto-generated SQL INSERT statements (literal values)",
        f"-- Schema: {schema_name}",
        "-- Generated by svc-ai-schema-mapper",
        "",
        "BEGIN;",
        "",
    ]

    total_rows = 0
    for table_name in insertion_order:
        if table_name not in cleaned_tables:
            continue

        records = cleaned_tables[table_name]

        if hasattr(records, "to_dict"):
            records = records.to_dict(orient="records")

        if not records:
            continue

        table_sql, row_count = _generate_table_inserts(
            table_name,
            records,
            schema_name,
        )
        total_rows += row_count
        sql_lines.append(table_sql)
        sql_lines.append("")

    sql_lines.extend([
        "COMMIT;",
        "",
        f"-- End of SQL INSERT statements ({total_rows} rows)",
    ])

    sql_script = "\n".join(sql_lines)
    logger.info(
        f"[SQL Exporter] Generated SQL script ({len(sql_script)} bytes, {total_rows} rows)"
    )

    return sql_script


def _determine_insertion_order(
    table_names: List[str],
    confirmed_hierarchies: List[Dict],
) -> List[str]:
    """Topological sort: parent tables before children (FK targets first)."""

    dependencies = {table: set() for table in table_names}

    for hierarchy in confirmed_hierarchies:
        source = hierarchy.get("source_table") if isinstance(hierarchy, dict) else getattr(
            hierarchy, "source_table", None
        )
        target = hierarchy.get("target_table") if isinstance(hierarchy, dict) else getattr(
            hierarchy, "target_table", None
        )

        if source in dependencies and target in dependencies:
            dependencies[source].add(target)

    ordered: List[str] = []
    visited: set[str] = set()
    visiting: set[str] = set()

    def visit(table: str) -> None:
        if table in visited:
            return
        if table in visiting:
            logger.warning(f"[SQL Exporter] Circular dependency detected: {table}")
            return

        visiting.add(table)

        for dep in dependencies.get(table, set()):
            visit(dep)

        visiting.remove(table)
        visited.add(table)
        ordered.append(table)

    for table in table_names:
        visit(table)

    return ordered


def _quote_ident(name: str) -> str:
    if _SAFE_IDENT.match(str(name)):
        return str(name)
    escaped = str(name).replace('"', '""')
    return f'"{escaped}"'


def _sql_literal(value: Any) -> str:
    """Format a Python value as a PostgreSQL SQL literal."""
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if value != value or value in (float("inf"), float("-inf")):
            return "NULL"
        return repr(value)
    if isinstance(value, Decimal):
        return str(value)
    if isinstance(value, UUID):
        return f"'{value}'"
    if isinstance(value, datetime):
        return f"'{value.isoformat()}'"
    if isinstance(value, date):
        return f"'{value.isoformat()}'"
    if isinstance(value, (dict, list)):
        payload = json.dumps(value, default=str, ensure_ascii=False).replace("'", "''")
        return f"'{payload}'"
    text = str(value).replace("'", "''")
    return f"'{text}'"


def _generate_table_inserts(
    table_name: str,
    records: List[Dict],
    schema_name: str,
) -> tuple[str, int]:
    """Generate one INSERT per row with literal VALUES."""

    if not records:
        return "", 0

    columns = list(records[0].keys())
    column_list = ", ".join(_quote_ident(c) for c in columns)
    qualified_table = f"{_quote_ident(schema_name)}.{_quote_ident(table_name)}"

    sql_lines = [
        f"-- Insert {len(records)} rows into {schema_name}.{table_name}",
    ]

    for record in records:
        values = ", ".join(_sql_literal(record.get(col)) for col in columns)
        # ON CONFLICT DO NOTHING: new rows are appended; a row whose key already exists
        # (e.g. an existing site_id) is skipped so existing data is preserved and the
        # batch never aborts on a duplicate key.
        sql_lines.append(
            f"INSERT INTO {qualified_table} ({column_list}) VALUES ({values}) "
            f"ON CONFLICT DO NOTHING;"
        )

    sql_lines.append("")
    return "\n".join(sql_lines), len(records)
