#!/usr/bin/env python3
"""Generate idempotent seed SQL for the GLOBAL UDR catalog tables from the ontology.

Reads canonical_entities.json + synonyms.json and emits seed_udr_catalog.sql with
upserts for:
  - plenum_cafm.udr_canonical_table   (ON CONFLICT canonical_table)
  - plenum_cafm.udr_canonical_column  (ON CONFLICT canonical_table, canonical_column)
  - plenum_cafm.udr_synonym           (INSERT ... WHERE NOT EXISTS — no unique key)

These three catalogs are GLOBAL (admin-level), not per-org, matching the PRD's
"canonical UDR target structure maintained at global admin level". Relationships
(relationships.json) are NOT seeded here — they are loaded at runtime by
ontology_loader and written per-run into udr_relationship (provenance=schema_defined).

Run AFTER udr_phase1_schema.sql. Stdlib only.  Usage: python seed_udr_catalog.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "seed_udr_catalog.sql")


def _load(name):
    with open(os.path.join(HERE, name), "r", encoding="utf-8") as fh:
        return json.load(fh)


def q(s):
    """SQL single-quote a string (None -> NULL)."""
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def jb(obj):
    """JSONB literal."""
    return "'" + json.dumps(obj, ensure_ascii=False).replace("'", "''") + "'::jsonb"


def build():
    entities = _load("canonical_entities.json")["entities"]
    syn = _load("synonyms.json")
    lines = [
        "-- AUTO-GENERATED by seed_udr_catalog.py — do not hand-edit.",
        "-- Seeds the GLOBAL UDR catalog from the ontology. Idempotent. Run after udr_phase1_schema.sql.",
        "SET search_path TO plenum_cafm, public;",
        "BEGIN;",
        "",
        "-- ── udr_canonical_table ─────────────────────────────────────────",
    ]
    for e in entities:
        cols = e.get("standard_columns", [])
        lines.append(
            "INSERT INTO plenum_cafm.udr_canonical_table "
            "(canonical_table, hierarchy_level, description, primary_key_column, standard_columns, is_reference_table) VALUES ("
            f"{q(e['canonical_table'])}, {q(e.get('hierarchy_level'))}, {q(e.get('description'))}, "
            f"{q(e.get('primary_key'))}, {jb(cols)}, {str(bool(e.get('is_reference_table'))).upper()})"
            " ON CONFLICT (canonical_table) DO UPDATE SET hierarchy_level=EXCLUDED.hierarchy_level, "
            "description=EXCLUDED.description, primary_key_column=EXCLUDED.primary_key_column, "
            "standard_columns=EXCLUDED.standard_columns, is_reference_table=EXCLUDED.is_reference_table, "
            "updated_at=now();"
        )

    lines += ["", "-- ── udr_canonical_column ────────────────────────────────────────"]
    for e in entities:
        for c in e.get("standard_columns", []):
            lines.append(
                "INSERT INTO plenum_cafm.udr_canonical_column "
                "(canonical_table, canonical_column, datatype, classification, cell_value_format, sample_values, references_table) VALUES ("
                f"{q(e['canonical_table'])}, {q(c['name'])}, {q(c.get('datatype'))}, {q(c.get('classification'))}, "
                f"{q(c.get('cell_value_format'))}, {jb(c.get('sample_values', []))}, {q(c.get('references_table'))})"
                " ON CONFLICT (canonical_table, canonical_column) DO UPDATE SET datatype=EXCLUDED.datatype, "
                "classification=EXCLUDED.classification, cell_value_format=EXCLUDED.cell_value_format, "
                "sample_values=EXCLUDED.sample_values, references_table=EXCLUDED.references_table;"
            )

    lines += ["", "-- ── udr_synonym (no unique key — guarded NOT EXISTS) ────────────"]

    def syn_row(system, term, kind, table, col, conf):
        where = (
            f"cmms_system={q(system)} AND source_term={q(term)} AND target_kind={q(kind)} "
            f"AND coalesce(canonical_table,'')=coalesce({q(table)},'') "
            f"AND coalesce(canonical_column,'')=coalesce({q(col)},'')"
        )
        return (
            "INSERT INTO plenum_cafm.udr_synonym "
            "(cmms_system, source_term, target_kind, canonical_table, canonical_column, confidence) "
            f"SELECT {q(system)}, {q(term)}, {q(kind)}, {q(table)}, {q(col)}, {conf} "
            f"WHERE NOT EXISTS (SELECT 1 FROM plenum_cafm.udr_synonym WHERE {where});"
        )

    for s in syn["table_synonyms"]:
        lines.append(syn_row(s["cmms_system"], s["source_term"], "table",
                             s.get("canonical_table"), None, s.get("confidence", "NULL")))
    for s in syn["column_synonyms"]:
        lines.append(syn_row(s["cmms_system"], s["source_term"], "column",
                             s.get("canonical_table"), s.get("canonical_column"), s.get("confidence", "NULL")))

    lines += ["", "COMMIT;", ""]
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    return len(entities), sum(len(e.get("standard_columns", [])) for e in entities), \
        len(syn["table_synonyms"]) + len(syn["column_synonyms"])


if __name__ == "__main__":
    t, c, s = build()
    print(f"Wrote {os.path.basename(OUT)}: {t} tables, {c} columns, {s} synonyms")
