package outputs

import (
	"bufio"
	"fmt"
	"strconv"
	"strings"

	"hoistra/engine/internal/cell"
)

// insertionOrder is sql_exporter._determine_insertion_order: parents (FK targets) first. Python
// visits a table's parents in set order, which differs from one process to the next; the engine
// visits them in the order the hierarchies name them.
func insertionOrder(names []string, hier []Hierarchy) []string {
	known := map[string]bool{}
	for _, n := range names {
		known[n] = true
	}
	deps := map[string][]string{}
	for _, h := range hier {
		s, ok1 := sp(h.SourceTable)
		t, ok2 := sp(h.TargetTable)
		if !ok1 || !ok2 || !known[s] || !known[t] {
			continue
		}
		dup := false
		for _, d := range deps[s] {
			if d == t {
				dup = true
				break
			}
		}
		if !dup {
			deps[s] = append(deps[s], t)
		}
	}
	var ordered []string
	visited, visiting := map[string]bool{}, map[string]bool{}
	var visit func(string)
	visit = func(t string) {
		if visited[t] || visiting[t] {
			return
		}
		visiting[t] = true
		for _, d := range deps[t] {
			visit(d)
		}
		delete(visiting, t)
		visited[t] = true
		ordered = append(ordered, t)
	}
	for _, n := range names {
		visit(n)
	}
	return ordered
}

// identRune is a character of [a-z_] / [a-z0-9_] under re.IGNORECASE (Unicode): the ASCII
// letters, and the four non-ASCII letters that case-fold onto them.
func identRune(r rune, first bool) bool {
	switch {
	case r == '_', r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z':
		return true
	case r == 'İ', r == 'ı', r == 'ſ', r == 'K':
		return true
	case r >= '0' && r <= '9':
		return !first
	}
	return false
}

// quoteIdent is sql_exporter._quote_ident (re.match with `$`, which also matches before a final "\n").
func quoteIdent(name string) string {
	body := strings.TrimSuffix(name, "\n")
	ok := body != ""
	for i, r := range []rune(body) {
		if !identRune(r, i == 0) {
			ok = false
			break
		}
	}
	if ok {
		return name
	}
	return `"` + strings.ReplaceAll(name, `"`, `""`) + `"`
}

func sqlLiteral(c cell.Cell) string {
	switch c.K {
	case cell.Null:
		return "NULL"
	case cell.Bool:
		if c.I != 0 {
			return "TRUE"
		}
		return "FALSE"
	case cell.Int:
		return strconv.FormatInt(c.I, 10)
	}
	return "'" + strings.ReplaceAll(c.S, "'", "''") + "'"
}

// writeSQL is export_to_sql over the routed tables, then the B22.1 lookup blocks.
func writeSQL(w *bufio.Writer, routes []*routed, hier []Hierarchy, schema string, blocks []string) {
	byDest := map[string]*routed{}
	names := make([]string, len(routes))
	for i, r := range routes {
		byDest[r.dest] = r
		names[i] = r.dest
	}
	w.WriteString("-- Auto-generated SQL INSERT statements (literal values)\n")
	w.WriteString("-- Schema: " + schema + "\n")
	w.WriteString("-- Generated by svc-ai-schema-mapper\n\nBEGIN;\n\n")
	total := 0
	for _, name := range insertionOrder(names, hier) {
		r := byDest[name]
		if r == nil || r.rows() == 0 {
			continue
		}
		var first *table
		for _, p := range r.parts {
			if p.rows() > 0 {
				first = p
				break
			}
		}
		cols := first.cols()
		quoted := make([]string, len(cols))
		for i, c := range cols {
			quoted[i] = quoteIdent(c)
		}
		head := "INSERT INTO " + quoteIdent(schema) + "." + quoteIdent(name) + " (" + strings.Join(quoted, ", ") + ") VALUES ("
		fmt.Fprintf(w, "-- Insert %d rows into %s.%s\n", r.rows(), schema, name)
		for _, p := range r.parts {
			idx := make([]int, len(cols))
			for i, c := range cols {
				idx[i] = p.t.ColumnIndex(c)
			}
			for row := 0; row < p.rows(); row++ {
				w.WriteString(head)
				for i := range cols {
					if i > 0 {
						w.WriteString(", ")
					}
					if idx[i] < 0 {
						w.WriteString("NULL")
					} else {
						w.WriteString(sqlLiteral(p.at(idx[i], row)))
					}
				}
				w.WriteString(") ON CONFLICT DO NOTHING;\n")
			}
		}
		// The table's lines end with its own "" element, and export_to_sql adds a "" after it.
		w.WriteString("\n\n")
		total += r.rows()
	}
	fmt.Fprintf(w, "COMMIT;\n\n-- End of SQL INSERT statements (%d rows)", total)
	if len(blocks) > 0 {
		w.WriteString("\n\n-- ============================================================\n")
		fmt.Fprintf(w, "-- SECTION: Shared-attribute lookup tables (%d) + FK rewrites (B22.1)\n", len(blocks))
		w.WriteString("-- Attribute promoted to a lookup PK; source columns rewritten as FKs.\n")
		w.WriteString("-- ============================================================\n\n")
		w.WriteString(strings.Join(blocks, "\n\n"))
		w.WriteString("\n")
	}
}
