"""AUTO-GENERATED from docs/FM_Ontology_Reference_v1.0.docx + plenum_cafm schema.

Complete FM crosswalk: per-platform CMMS/CAFM/EAM column aliases mapped to the
REAL plenum_cafm column on each entity's destination table. Consumed by the
deterministic mapper's table-scoped alias strategy. Do not edit by hand.
Regenerate with scripts/gen_fm_crosswalk.py.
"""

# real_table -> {platform alias (normalized) -> real column}
FM_COLUMN_ALIASES_BY_TABLE = {
    'asset_categories': {'asset_type_name': 'category_name', 'klbez': 'category_name', 'typename': 'category_name'},
    'assets': {'aedat': 'updated_at', 'asset_tag': 'barcode', 'asset_type_id': 'asset_type', 'assetnum': 'asset_code', 'assettag': 'barcode', 'assettype': 'asset_type', 'assettypeid': 'asset_type', 'created_date': 'created_at', 'createddate': 'created_at', 'date_installed': 'installation_date', 'description': 'notes', 'eq_barcode': 'barcode', 'eq_id': 'asset_code', 'eq_name': 'asset_name', 'eqktx': 'asset_name', 'eqstd': 'asset_type', 'eqtyp': 'asset_type', 'equnr': 'asset_code', 'erdat': 'created_at', 'externalobjectidentifier': 'barcode', 'herst': 'manufacturer', 'inbdt': 'installation_date', 'install_date': 'installation_date', 'installationdate': 'installation_date', 'installdate': 'installation_date', 'longdescription': 'notes', 'manufacturername': 'manufacturer', 'model_num': 'model_number', 'modelnum': 'model_number', 'modelnumber': 'model_number', 'modified_date': 'updated_at', 'modifieddate': 'updated_at', 'parent': 'parent_asset_id', 'parent_eq_id': 'parent_asset_id', 'pltxt': 'notes', 'remarks': 'notes', 'rm_id': 'location_id', 'serge': 'serial_number', 'serial_num': 'serial_number', 'serialnum': 'serial_number', 'serialnumber': 'serial_number', 'space_id': 'location_id', 'spaceid': 'location_id', 'superiorequipment': 'parent_asset_id', 'tristatuscl': 'status', 'typbz': 'model_number', 'ustmp': 'status', 'warranty_exp': 'warranty_expiry', 'warranty_expiry_date': 'warranty_expiry', 'warrantyenddate': 'warranty_expiry', 'warrantyexpdate': 'warranty_expiry', 'warrantyexpiry': 'warranty_expiry'},
    'certificates': {'assetid': 'asset_id', 'assetnum': 'asset_id', 'certdate': 'uploaded_at', 'certificatetype': 'certificate_type', 'compliancestatus': 'status', 'date_expires': 'expiry_date', 'date_issued': 'uploaded_at', 'eq_id': 'asset_id', 'equnr': 'asset_id', 'expirationdate': 'expiry_date', 'expirydate': 'expiry_date', 'inspectiontype': 'certificate_type', 'issue_date': 'uploaded_at', 'issuedate': 'uploaded_at'},
    'files': {'changedate': 'uploaded_at', 'created_date': 'uploaded_at', 'createddate': 'uploaded_at', 'dktxt': 'name', 'document_name': 'name', 'dokvr': 'mime_type', 'dr_desc': 'name', 'entityid': 'entity_id', 'entitytype': 'entity_type', 'erdat': 'uploaded_at', 'file_type': 'mime_type', 'filepath': 'blob_url', 'filetype': 'mime_type', 'objectkey': 'entity_id', 'objecttype': 'entity_type', 'related_entity_id': 'entity_id', 'related_entity_type': 'entity_type', 'storage_path': 'blob_url', 'storagepath': 'blob_url', 'url': 'blob_url', 'urltype': 'mime_type'},
    'locations': {'bl_name': 'name', 'building_name': 'name', 'building_type': 'type', 'buildingtype': 'type', 'changedate': 'created_at', 'created_date': 'created_at', 'createddate': 'created_at', 'elevation': 'level', 'fl_id': 'level', 'floornumber': 'level', 'level_number': 'level', 'parent': 'parent_location_id', 'parent_id': 'parent_location_id', 'parent_space_id': 'parent_location_id', 'parentpropertyid': 'site_id', 'parentspace': 'parent_location_id', 'rm_name': 'name', 'rm_type': 'type', 'roomcategory': 'type', 'siteid': 'site_id', 'space_name': 'name', 'space_type': 'type', 'spacetype': 'type', 'trinametx': 'name'},
    'maintenance_plans': {'assetid': 'asset_id', 'assetnum': 'asset_id', 'changedate': 'created_at', 'created_date': 'created_at', 'createddate': 'created_at', 'eq_id': 'asset_id', 'equnr': 'asset_id', 'frequency': 'frequency_value', 'frequencytype': 'frequency_type', 'frequencyvalue': 'frequency_value', 'frequnit': 'frequency_type', 'ktext': 'description', 'nextdate': 'next_due_date', 'nextduedate': 'next_due_date', 'pm_date_next': 'next_due_date', 'pm_desc': 'description', 'pm_freq': 'frequency_value', 'pm_status': 'status', 'schedule_name': 'description', 'triggertype': 'frequency_type', 'zykl1': 'frequency_value'},
    'ppm_schedules': {'assetid': 'asset_id', 'assetnum': 'asset_id', 'changedate': 'created_at', 'created_date': 'created_at', 'createddate': 'created_at', 'eq_id': 'asset_id', 'equnr': 'asset_id', 'longdescription': 'task_description', 'ltxt': 'task_description', 'taskdescription': 'task_description'},
    'sites': {'changeby': 'created_at', 'created_date': 'created_at', 'createddate': 'created_at', 'erdat': 'created_at', 'gross_area_sqm': 'gfa_sqm', 'grossarea': 'gfa_sqm', 'land1': 'country', 'measureunit': 'gfa_sqm', 'ort01': 'city', 'propertytype': 'site_type', 'sitecode': 'site_code', 'stat': 'status', 'trinametx': 'site_name', 'tristatuscl': 'status'},
    'technicians': {'changedate': 'created_at', 'created_date': 'created_at', 'createddate': 'created_at', 'status': 'availability_status', 'tristatuscl': 'availability_status'},
    'vendor_contracts': {'annual_value': 'contract_value', 'annualvalue': 'contract_value', 'changedate': 'created_at', 'created_date': 'created_at', 'createddate': 'created_at', 'ct_desc': 'contract_name', 'ct_end': 'contract_end', 'ct_start': 'contract_start', 'ct_status': 'status', 'end_date': 'contract_end', 'enddate': 'contract_end', 'erdat': 'created_at', 'kdatb': 'contract_start', 'kdate': 'contract_end', 'ktext': 'contract_name', 'lifnr': 'vendor_id', 'netwr': 'contract_value', 'revisionnum': 'contract_value', 'start_date': 'contract_start', 'startdate': 'contract_start', 'vendor': 'vendor_id', 'vendorid': 'vendor_id', 'vn_id': 'vendor_id'},
    'vendors': {'address1': 'address', 'address_line_1': 'address', 'changedate': 'created_at', 'company': 'vendor_code', 'contactemail': 'email', 'created_date': 'created_at', 'createddate': 'created_at', 'erdat': 'created_at', 'lifnr': 'vendor_code', 'name1': 'vendor_name', 'ort01': 'city', 'postalcode': 'postal_code', 'postcode': 'postal_code', 'primary_contact_email': 'email', 'primary_contact_phone': 'phone', 'pstlz': 'postal_code', 'sperr': 'status', 'stras': 'address', 'vn_address': 'address', 'vn_city': 'city', 'vn_id': 'vendor_code', 'vn_name': 'vendor_name', 'vn_zip': 'postal_code'},
    'work_orders': {'actfinish': 'completed_at', 'actualcompletiondate': 'completed_at', 'actualhours': 'actual_hours', 'actualpartscost': 'cost_parts_aed', 'assetid': 'asset_id', 'assetnum': 'asset_id', 'assignedto': 'assigned_technician', 'aufnr': 'work_order_id', 'completion_date': 'completed_at', 'created_date': 'created_at', 'createddate': 'created_at', 'date_completed': 'completed_at', 'date_requested': 'created_at', 'date_required': 'scheduled_date', 'eq_id': 'asset_id', 'equnr': 'asset_id', 'erdat': 'created_at', 'fault_description': 'description', 'faultdescription': 'description', 'idat2': 'completed_at', 'ismnw': 'actual_hours', 'iwerk': 'scheduled_date', 'ktext': 'title', 'labor_id': 'assigned_technician', 'laborcode': 'assigned_technician', 'labour_hours': 'actual_hours', 'lifnr': 'assigned_vendor', 'longdescription': 'description', 'ltxt': 'description', 'matusetotalcost': 'cost_parts_aed', 'modified_date': 'updated_at', 'modifieddate': 'updated_at', 'parts_cost': 'cost_parts_aed', 'pernr': 'assigned_technician', 'priok': 'priority', 'problem_cause': 'description', 'raised_date': 'created_at', 'regularhrs': 'actual_hours', 'reportdate': 'created_at', 'required_by_date': 'scheduled_date', 'resolution_notes': 'solution', 'resolutionnotes': 'solution', 'resource_id': 'assigned_technician', 'rm_id': 'location_id', 'space_id': 'location_id', 'spaceid': 'location_id', 'stat': 'status', 'targcompdate': 'scheduled_date', 'targetcompletiondate': 'scheduled_date', 'tplnr': 'location_id', 'vendor_id': 'assigned_vendor', 'vendorid': 'assigned_vendor', 'vn_id': 'assigned_vendor', 'woactivity_description': 'solution', 'wonum': 'work_order_id', 'wopriority': 'priority', 'workorder_ref': 'work_order_id', 'wr_desc': 'title', 'wr_id': 'work_order_id', 'wr_priority': 'priority', 'wr_status': 'status'},
}

# canonical FM entity -> primary real plenum_cafm table
FM_ENTITY_TO_TABLE = {
    'asset': 'assets',
    'asset_type': 'asset_categories',
    'building': 'locations',
    'compliance_certificate': 'certificates',
    'contract': 'vendor_contracts',
    'document': 'files',
    'ppm_schedule': 'maintenance_plans',
    'resource': 'technicians',
    'site': 'sites',
    'space': 'locations',
    'vendor': 'vendors',
    'work_order': 'work_orders',
}
