"""AUTO-GENERATED from plenum_cafm.csv — do not edit by hand.

Authoritative plenum_cafm destination schema + schema-grounded aliases.
Regenerate with scripts/gen_plenum_cafm_schema.py.
"""

# 146 base tables, 1437 columns
TABLES = {
    'accounts': ['id', 'organization_id', 'code', 'description', 'created_at', 'updated_at', 'intcode', 'intsiteid', 'strname', 'strdescription', 'intconsumesassetid', 'intbompartcontrolid', 'intbomcontrolid', 'intstockid', 'intupdated', 'strcode', 'dtmdate', 'dbltotalcost', 'intbusinessid', 'intcyclecountid', 'intpurchaseorderlineitemid', 'intreceiptid', 'streventcode', 'intassignedtouserid', 'intpurchaseorderstatusid', 'dblsubtotal', 'intparentid', 'intbusinessroletypeid', 'intsubmittedbyuserid', 'dtmdatesubmitted', 'dblmeterreading', 'strcontents', 'intfileid', 'intregionid', 'strassignedusers', 'strassigneduserids', 'intrequestedbyuserid', 'intworkorderstatusid', 'strassets', 'strassetids', 'intprojectid', 'strsolution', 'strproblem', 'strcompletionnotes', 'intuserid', 'intcountryid', 'strnotes', 'strwebsite', 'strfax', 'strpostalcode', 'strprovince', 'strcity', 'straddress', 'intreceiptstatusid', 'strlink', 'intsize', 'intmovestatusid'],
    'activity_actions': ['id', 'entry_id', 'organization_id', 'kind', 'label', 'options', 'status', 'chosen_option_id', 'resolution_note', 'deadline_at', 'resolved_at', 'created_at', 'updated_at'],
    'activity_log_entries': ['id', 'organization_id', 'session_id', 'trigger', 'trigger_detail', 'outcome', 'status', 'notif_color', 'refs', 'processing_log', 'read', 'created_at', 'updated_at'],
    'agent_audit_log': ['id', 'agent_id', 'domain', 'asset_code', 'bound_validation_passed', 'run_1_output', 'run_2_output', 'run_3_output', 'run_1_valid', 'run_2_valid', 'run_3_valid', 'runs_agreed', 'winner_status', 'winner_confidence', 'hard_rules_fired', 'final_status', 'confidence_gate_passed', 'requires_human_review', 'model_used', 'tokens_total', 'cost_usd', 'timestamp'],
    'alembic_version': ['version_num'],
    'asset_businesses': ['id', 'asset_id', 'vendor_id', 'business_group_id', 'classification_id'],
    'asset_categories': ['id', 'organization_id', 'category_name', 'parent_category_id'],
    'asset_documents': ['id', 'asset_id', 'file_url', 'document_type', 'uploaded_by', 'uploaded_at'],
    'asset_event_types': ['id', 'organization_id', 'event_code', 'name'],
    'asset_events': ['id', 'asset_id', 'event_type_id', 'description', 'work_order_id', 'recorded_by', 'recorded_at'],
    'asset_offline_log': ['id', 'asset_id', 'offline_reason_id', 'online_reason_id', 'went_offline_at', 'came_online_at', 'downtime_minutes', 'work_order_id', 'recorded_by', 'notes'],
    'asset_readings': ['id', 'organization_id', 'asset_id', 'reading_type', 'value', 'unit', 'recorded_at', 'anomaly_flag'],
    'asset_users': ['id', 'asset_id', 'user_id'],
    'asset_warranties': ['id', 'asset_id', 'description', 'provider', 'start_date', 'expiry_date', 'coverage_notes', 'document_url', 'created_at', 'updated_at'],
    'assets': ['id', 'organization_id', 'site_id', 'location_id', 'category_id', 'asset_name', 'asset_code', 'serial_number', 'barcode', 'qr_code', 'manufacturer', 'model', 'model_number', 'make', 'installation_date', 'warranty_expiry', 'status', 'health_score', 'criticality', 'is_online', 'location', 'location_code', 'parent_asset_id', 'is_site', 'notes', 'raw_metadata', 'external_asset_id', 'inventory_code', 'aisle', 'row', 'bin_number', 'stock_location', 'charge_department_id', 'project_id', 'account_code', 'account_id', 'category', 'created_at', 'updated_at', 'timezone', 'country_id', 'document_ids', 'asset_type'],
    'audit_logs': ['id', 'organization_id', 'user_id', 'action', 'entity_type', 'entity_id', 'metadata', 'created_at'],
    'billing_terms': ['id', 'organization_id', 'name', 'net_days'],
    'bom_group_parts': ['id', 'bom_group_id', 'part_id', 'quantity'],
    'bom_groups': ['id', 'organization_id', 'name', 'description', 'created_at', 'updated_at'],
    'business_classifications': ['id', 'organization_id', 'name'],
    'business_groups': ['id', 'organization_id', 'name'],
    'canonical_registry': ['version', 'schema_hash', 'registry_json', 'canonical_count', 'learned_count', 'created_at'],
    'certificates': ['certificate_id', 'asset_id', 'certificate_type', 'certificate_name', 'expiry_date', 'status', 'uploaded_at'],
    'charge_departments': ['id', 'organization_id', 'code', 'description', 'created_at', 'updated_at'],
    'claude_api_usage': ['id', 'ingestion_id', 'query_id', 'service', 'agent_id', 'model', 'tokens_in', 'tokens_out', 'cache_read_tokens', 'cost_usd', 'latency_ms', 'timestamp'],
    'claude_budget_config': ['id', 'period', 'limit_usd', 'alert_threshold_pct', 'auto_pause', 'is_active', 'created_at', 'updated_at'],
    'connectors': ['id', 'name', 'source_type', 'connection_params', 'config_encrypted', 'options', 'description', 'created_by', 'created_at', 'updated_at', 'is_active'],
    'corrections_log': ['id', 'ingestion_id', 'field_path', 'original_value', 'corrected_value', 'correction_type', 'reviewer_id', 'timestamp'],
    'countries': ['id', 'name', 'code'],
    'currencies': ['id', 'name', 'symbol', 'iso_code'],
    'cycle_counts': ['id', 'organization_id', 'site_id', 'status', 'counted_by', 'started_at', 'completed_at'],
    'data': ['id', 'organization_id', 'asset_name', 'asset_code', 'status', 'last_price_currency', 'site_id', 'site_name', 'site_type', 'country', 'city', 'floors', 'gfa_sqm', 'occupancy_profile', 'handover_date', 'inspection_id', 'category', 'assigned_tech_id', 'findings_count', 'criticality', 'notes', 'make', 'model', 'serial', 'install_date', 'sm_priority', 'wo_code', 'wo_title', 'wo_priority', 'created_at', 'due_date', 'technician', 'wo_type', 'responded_at', 'fault_code', 'cause_code', 'resolution_code', 'labor_minutes', 'travel_minutes', 'sla_response_target_mins', 'sla_response_actual_mins', 'sla_breached', 'cost_parts_aed', 'cost_vendor_aed', 'vendor_id'],
    'document_chunks': ['id', 'ingestion_id', 'source_filename', 'doc_type', 'chunk_index', 'chunk_text', 'embedding', 'heading', 'metadata', 'created_at'],
    'document_generation_log': ['id', 'request_text', 'intent_type', 'document_type', 'document_plan_json', 'plan_validation_passed', 'output_format', 'output_blob_url', 'data_sources', 'spot_checks_run', 'spot_checks_passed', 'eval_score', 'plan_runs_agreed', 'held_for_review', 'model_used', 'tokens_in', 'tokens_out', 'cost_usd', 'render_ms', 'user_id', 'timestamp'],
    'field_maps': ['id', 'connector_id', 'source_field', 'target_field', 'transform_fn', 'created_at'],
    'fiix_ingestion_jobs': ['id', 'organization_id', 'created_by', 'status', 'current_step', 'progress_pct', 'total_records_fetched', 'fetch_stats', 'fetch_errors', 'total_records_preprocessed', 'preprocess_stats', 'preprocess_warnings', 'total_records_written', 'write_results', 'write_errors', 'error_message', 'error_node', 'started_at', 'completed_at', 'created_at'],
    'fiix_schema_cache': ['id', 'subdomain_key', 'subdomain', 'mapper_config', 'table_count', 'column_count', 'created_at', 'updated_at'],
    'files': ['id', 'organization_id', 'name', 'blob_url', 'file_size_bytes', 'mime_type', 'entity_type', 'entity_id', 'uploaded_by', 'uploaded_at'],
    'import_errors': ['id', 'job_id', 'row_num', 'raw_data', 'error_msg', 'created_at'],
    'import_jobs': ['id', 'connector_id', 'status', 'table_name', 'conflict_mode', 'schedule', 'cron_expr', 'total_rows', 'imported_rows', 'skipped_rows', 'error_count', 'started_at', 'finished_at', 'created_at', 'created_by', 'is_rolled_back'],
    'ingestion_audit_log': ['id', 'ingestion_id', 'event_type', 'model_used', 'prompt_version', 'eval_score', 'rules_violations', 'reviewer_id', 'decision', 'corrected_json', 'timestamp'],
    'ingestion_documents': ['id', 'tenant_id', 'source_type', 'agent_id', 'original_filename', 'blob_url', 'file_hash_sha256', 'page_count', 'intermediate_json', 'final_json', 'status', 'confidence_overall', 'eval_score', 'model_used', 'prompt_template_id', 'tokens_in', 'tokens_out', 'cache_read_tokens', 'cost_usd', 'processing_ms', 'uploaded_by', 'uploaded_at', 'processed_at'],
    'inspections': ['id', 'asset_id', 'asset_code', 'inspector', 'inspection_date', 'finding_type', 'observations', 'risk_level', 'created_at'],
    'inventory_transactions': ['id', 'part_id', 'transaction_type', 'quantity', 'reference_type', 'reference_id', 'created_at', 'unit_cost', 'total_cost', 'notes', 'tx_type_id'],
    'known_issues': ['id', 'manufacturer', 'model', 'issue_description', 'occurrence_count', 'avg_repair_cost', 'solutions', 'last_occurred'],
    'locations': ['id', 'organization_id', 'site_id', 'name', 'type', 'parent_location_id', 'level', 'address', 'city', 'province', 'postal_code', 'country', 'timezone', 'created_at', 'document_ids'],
    'maintenance_history': ['id', 'asset_id', 'work_order_id', 'performed_by', 'performed_at', 'notes'],
    'maintenance_plans': ['id', 'organization_id', 'asset_id', 'maintenance_type', 'frequency_type', 'frequency_value', 'next_due_date', 'created_at', 'sm_code', 'description', 'maintenance_type_id', 'priority_id', 'task_group_id', 'status', 'project_id', 'charge_department_id', 'updated_at', 'sm_status_id', 'account_id'],
    'maintenance_types': ['id', 'organization_id', 'name', 'description', 'created_at', 'updated_at'],
    'mapping_templates': ['id', 'organization_id', 'source_system', 'table_name', 'version', 'name', 'config_json', 'is_active', 'created_by', 'created_at', 'updated_at'],
    'meter': ['id', 'asset_id', 'site_id', 'critical_flag', 'inspector_tech_id', 'timestamp', 'findings_count', 'inspection_id', 'inspection_type', 'notes', 'created_at', 'updated_at'],
    'meter_reading_units': ['id', 'organization_id', 'name', 'symbol', 'precision', 'created_at'],
    'migration_field_mappings': ['id', 'migration_id', 'source_field', 'source_fields', 'merge_strategy', 'target_field', 'confidence', 'tier', 'rationale', 'langsmith_run_id', 'created_at', 'sample_values', 'transformation', 'reviewer_id', 'decided_at'],
    'migration_hierarchy': ['id', 'migration_id', 'source_table', 'target_table', 'fk_source_column', 'fk_target_column', 'relationship_type', 'confidence', 'data_match_rate', 'is_valid', 'cycle_detected', 'created_at'],
    'migration_jobs': ['id', 'organization_id', 'cmms_name', 'source_filename', 'source_blob_url', 'mapping_doc_id', 'status', 'current_step', 'progress_pct', 't1_mapped_count', 't2_auto_count', 't2_human_count', 't2_multi_merge_count', 'unmapped_count', 'total_fields', 'total_records', 'orphan_count', 'cycle_count', 'output_json_url', 'output_csv_url', 'output_sql_url', 'migration_report_url', 'mapping_flow_url', 'error_message', 'started_at', 'completed_at', 'error_timestamp', 'pending_gate_type', 'pending_gate_payload', 'node_logs', 'field_mapping_draft'],
    'misc_cost_types': ['id', 'organization_id', 'name'],
    'misc_costs': ['id', 'work_order_id', 'misc_cost_type_id', 'description', 'amount', 'currency_id', 'created_by', 'created_at'],
    'move_assets': ['id', 'move_id', 'asset_id'],
    'move_back_assets': ['id', 'move_back_id', 'asset_id'],
    'move_backs': ['id', 'organization_id', 'move_id', 'status_id', 'notes', 'created_at'],
    'move_statuses': ['id', 'organization_id', 'name'],
    'moves': ['id', 'organization_id', 'status_id', 'from_site_id', 'to_site_id', 'requested_by', 'notes', 'created_at'],
    'notifications': ['id', 'organization_id', 'user_id', 'title', 'message', 'type', 'entity_type', 'entity_id', 'is_read', 'created_at'],
    'orchestration_audit_log': ['id', 'asset_code', 'bound_passed', 'run_1_valid', 'run_2_valid', 'run_3_valid', 'runs_agreed', 'action', 'priority', 'confidence', 'reasoning', 'confidence_gate_passed', 'safety_passed', 'agent_results_jsonb', 'hard_rules_fired', 'model_used', 'tokens_total', 'cost_usd', 'timestamp'],
    'organizations': ['id', 'name', 'code', 'timezone', 'created_at', 'industry', 'address', 'country', 'status', 'updated_at'],
    'permissions': ['id', 'name', 'description'],
    'ppm_schedules': ['schedule_id', 'asset_id', 'asset_name', 'location', 'task_description', 'task_type', 'frequency', 'priority', 'estimated_duration_minutes', 'required_skills', 'required_parts', 'active', 'created_at'],
    'priorities': ['id', 'organization_id', 'name', 'sort_order', 'color_hex', 'created_at', 'updated_at'],
    'projects': ['id', 'organization_id', 'name', 'description', 'site_id', 'status', 'start_date', 'end_date', 'created_at', 'updated_at'],
    'prompt_ab_tests': ['id', 'template_a_id', 'template_b_id', 'status', 'accuracy_a', 'accuracy_b', 'winner_id', 'docs_processed', 'created_at', 'completed_at'],
    'prompt_templates': ['id', 'agent_id', 'doc_type', 'system_prompt', 'user_template', 'extraction_schema', 'version', 'accuracy_score', 'usage_count', 'avg_tokens', 'is_active', 'created_at', 'updated_at'],
    'purchase_order_additional_cost_types': ['id', 'organization_id', 'name'],
    'purchase_order_additional_costs': ['id', 'purchase_order_id', 'cost_type_id', 'description', 'amount'],
    'purchase_order_line_items': ['id', 'purchase_order_id', 'part_id', 'asset_id', 'description', 'quantity', 'unit_price', 'total_price', 'tax_rate'],
    'purchase_order_logs': ['id', 'purchase_order_id', 'user_id', 'action', 'logged_at'],
    'purchase_order_statuses': ['id', 'organization_id', 'name', 'is_closed_state', 'sort_order', 'created_at'],
    'purchase_orders': ['id', 'organization_id', 'po_code', 'supplier_id', 'status_id', 'status', 'site_id', 'charge_department_id', 'subtotal', 'tax_amount', 'total_amount', 'notes', 'created_by', 'created_at', 'received_at', 'updated_at', 'billing_term_id', 'currency_id'],
    'query_audit_log': ['id', 'query_text', 'intent_classified', 'retrieval_tier', 'docs_consulted', 'model_used', 'response_text', 'eval_score', 'output_format', 'tokens_in', 'tokens_out', 'cost_usd', 'latency_ms', 'user_id', 'timestamp'],
    'rca_actions': ['id', 'organization_id', 'description'],
    'rca_causes': ['id', 'organization_id', 'description'],
    'rca_grouping_actions': ['id', 'rca_grouping_id', 'rca_action_id', 'assigned_to', 'due_date', 'completed_at'],
    'rca_grouping_causes': ['id', 'rca_grouping_id', 'rca_cause_id'],
    'rca_groupings': ['id', 'work_order_id', 'problem_id', 'notes', 'created_at'],
    'rca_problems': ['id', 'organization_id', 'description'],
    'reasons_asset_offline': ['id', 'organization_id', 'name', 'description'],
    'reasons_asset_online': ['id', 'organization_id', 'name', 'description'],
    'receipt_line_items': ['id', 'receipt_id', 'po_line_item_id', 'part_id', 'quantity_ordered', 'quantity_received', 'notes'],
    'receipt_statuses': ['id', 'organization_id', 'name', 'is_closed_state'],
    'receipts': ['id', 'purchase_order_id', 'status_id', 'site_id', 'received_by', 'received_at', 'notes', 'created_at'],
    'review_queue': ['id', 'ingestion_id', 'field_path', 'extracted_value', 'confidence', 'routing_reason', 'reviewer_id', 'status', 'decision', 'corrected_value', 'locked_until', 'created_at', 'decided_at'],
    'rfq_line_items': ['id', 'rfq_id', 'part_id', 'description', 'quantity', 'unit_price', 'currency_id'],
    'rfq_statuses': ['id', 'organization_id', 'name'],
    'rfqs': ['id', 'organization_id', 'rfq_code', 'supplier_id', 'status_id', 'site_id', 'notes', 'created_by', 'created_at'],
    'role_permissions': ['id', 'role_id', 'permission_id'],
    'roles': ['id', 'organization_id', 'name', 'description'],
    'saved_spaces': ['id', 'organization_id', 'name', 'kind', 'created_by', 'created_at'],
    'schedule_triggers': ['id', 'maintenance_plan_id', 'trigger_type', 'interval_value', 'interval_unit', 'meter_interval', 'meter_unit_id', 'last_triggered_at', 'next_due_date', 'created_at'],
    'scheduled_maintenance_assets': ['id', 'maintenance_plan_id', 'asset_id'],
    'scheduled_maintenance_parts': ['id', 'maintenance_plan_id', 'part_id', 'quantity_required'],
    'scheduled_maintenance_statuses': ['id', 'organization_id', 'name', 'is_closed_state', 'sort_order'],
    'scheduled_maintenance_users': ['id', 'maintenance_plan_id', 'user_id'],
    'scheduled_tasks': ['id', 'task_group_id', 'maintenance_plan_id', 'description', 'estimated_hours', 'task_type', 'sort_order', 'asset_id', 'created_at'],
    'schema_mapping_field_mappings': ['id', 'schema_mapping_id', 'source_field', 'source_table', 'target_field', 'confidence', 'tier', 'rationale', 'mapped_at'],
    'schema_mapping_jobs': ['id', 'organization_id', 'external_cmms_name', 'schema_source', 'schema_format', 'status', 'current_node', 'progress_pct', 'total_tables', 'total_fields', 'tier1_mapped', 'tier2_auto_mapped', 'tier2_flagged', 'unmapped', 'detected_fk_count', 'hierarchy_depth', 'implicit_hierarchy_count', 'final_mapping_config', 'final_summary', 'mapping_coverage_pct', 'node_state_json', 'error_message', 'started_at', 'completed_at', 'last_updated_at', 'error_timestamp', 'pending_gate_type', 'pending_gate_payload', 'node_logs', 'output_json_url', 'output_csv_url', 'output_sql_url', 'new_schema_name'],
    'site_users': ['id', 'user_id', 'site_id'],
    'sites': ['site_id', 'organization_id', 'site_name', 'site_code', 'city', 'country', 'timezone', 'status', 'created_at', 'site_type', 'floors', 'gfa_sqm', 'occupancy_profile', 'id', 'completed_at', 'handover_date'],
    'sla_policies': ['id', 'organization_id', 'name', 'priority', 'response_time_minutes', 'resolution_time_minutes'],
    'spare_parts': ['id', 'organization_id', 'part_name', 'part_code', 'description', 'unit_price', 'stock_quantity', 'reorder_level', 'max_quantity', 'unit_of_measure', 'supplier_id', 'bom_group_id', 'updated_at'],
    'stock_cycle_counts': ['id', 'cycle_count_id', 'part_id', 'qty_expected', 'qty_counted', 'variance'],
    'stock_history': ['id', 'part_id', 'description', 'qty_change', 'qty_after', 'tx_type_id', 'changed_by', 'changed_at'],
    'stock_tx_types': ['id', 'organization_id', 'name', 'affects_qty'],
    'task_groups': ['id', 'organization_id', 'name', 'description', 'created_at', 'updated_at'],
    'technician_skills': ['id', 'technician_id', 'skill_name', 'skill_level'],
    'technicians': ['id', 'organization_id', 'user_id', 'base_location', 'availability_status', 'performance_score', 'created_at'],
    'transportation': ['id', 'priority', 'status', 'technician_id', 'technician_name', 'work_order_ref', 'allowance_per_diem_aed', 'distance_km', 'from_city', 'from_site_code', 'from_site_id', 'from_site_name', 'month', 'remarks', 'request_type', 'specialization', 'to_city', 'to_site_code', 'to_site_id', 'to_site_name', 'total_trip_cost_aed', 'transport_cost_aed', 'transport_mode', 'travel_date', 'travel_duration_hrs', 'trip_id', 'created_at', 'updated_at', 'organization_id'],
    'udr_entity_relationships': ['id', 'run_id', 'organization_id', 'src_entity', 'src_column', 'rel_type', 'dst_entity', 'dst_column', 'provenance', 'confidence', 'evidence', 'created_at', 'updated_at'],
    'udr_run_graph': ['id', 'run_id', 'organization_id', 'table_metadata', 'column_metadata', 'relationship_count', 'created_at', 'updated_at'],
    'udr_run_versions': ['id', 'session_id', 'organization_id', 'version_no', 'custom_name', 'phase', 'mapping_status', 'hierarchy_status', 'migration_ids', 'document_ids', 'batch_ids', 'snapshot', 'created_at'],
    'uploaded_files': ['id', 'original_filename', 'content_type', 'file_extension', 'file_size_bytes', 'blob_name', 'blob_url', 'connector_id', 'uploaded_by', 'created_at'],
    'user_certifications': ['id', 'user_id', 'name', 'description', 'issued_by', 'issued_date', 'expiry_date', 'document_url', 'created_at', 'updated_at'],
    'user_roles': ['id', 'user_id', 'role_id'],
    'users': ['id', 'organization_id', 'email', 'full_name', 'role', 'created_at', 'password_hash', 'last_login_at', 'email_verified', 'phone', 'phone2', 'personnel_code', 'hourly_rate', 'is_group', 'updated_at', 'status'],
    'vendor_contacts': ['id', 'vendor_id', 'name', 'email', 'phone', 'designation'],
    'vendor_contracts': ['id', 'organization_id', 'vendor_id', 'contract_name', 'contract_start', 'contract_end', 'contract_value', 'sla_terms', 'contract_document', 'status', 'created_at'],
    'vendors': ['id', 'organization_id', 'vendor_name', 'vendor_code', 'address', 'city', 'province', 'postal_code', 'country', 'phone', 'fax', 'website', 'email', 'notes', 'status', 'created_at', 'country_id', 'business_group_id', 'classification_id'],
    'wo_approval_requests': ['request_id', 'work_order_id', 'approval_type', 'approver', 'status', 'requested_at', 'responded_at', 'notes', 'level', 'step_order', 'risk_score', 'match_score', 'suggestion_source', 'unblocked_at'],
    'wo_approval_rules': ['rule_id', 'dimension', 'match_value', 'match_operator', 'match_threshold', 'match_threshold_upper', 'weight', 'active', 'created_at'],
    'wo_approval_suggestions': ['suggestion_id', 'work_order_id', 'fingerprint', 'source', 'confidence', 'match_score', 'risk_score', 'suggested_chain', 'accepted', 'created_at'],
    'wo_approval_thresholds': ['level', 'min_score', 'max_score', 'required_roles'],
    'wo_approver_routing': ['id', 'asset_category', 'user_id', 'approver_role', 'active', 'created_at'],
    'wo_assets': ['asset_id', 'asset_name', 'asset_type', 'location', 'manufacturer', 'model', 'serial_number', 'active', 'created_at'],
    'wo_chat_sessions': ['session_id', 'messages', 'context', 'source', 'created_at', 'last_activity'],
    'wo_journey_logs': ['id', 'jlog_id', 'work_order_id', 'status', 'current_step', 'completed', 'milestones', 'expected_timeline', 'actual_start', 'actual_end', 'asset_id', 'assigned_technician_id', 'estimated_cost', 'actual_cost', 'events', 'deviations', 'created_at', 'updated_at', 'source_system', 'journey_status', 'assigned_technician_name', 'team_members', 'estimated_duration_hours', 'actual_duration_hours', 'resources_used', 'status_change_history', 'milestone_history', 'completion_quality_score', 'customer_satisfaction_score', 'notes', 'created_by', 'updated_by'],
    'wo_locations': ['location_id', 'name', 'building', 'floor', 'zone', 'active', 'created_at'],
    'wo_status_history': ['history_id', 'work_order_id', 'from_status', 'to_status', 'changed_by', 'notes', 'changed_at'],
    'work_order_assets': ['id', 'work_order_id', 'asset_id'],
    'work_order_attachments': ['id', 'work_order_id', 'file_url', 'uploaded_by', 'uploaded_at', 'work_order_task_id'],
    'work_order_businesses': ['id', 'work_order_id', 'vendor_id'],
    'work_order_comments': ['id', 'work_order_id', 'user_id', 'comment', 'created_at'],
    'work_order_history': ['id', 'work_order_id', 'old_status', 'new_status', 'changed_by', 'changed_at', 'notes'],
    'work_order_parts': ['id', 'work_order_id', 'part_id', 'quantity_used', 'unit_cost', 'asset_id'],
    'work_order_statuses': ['id', 'organization_id', 'name', 'is_closed_state', 'sort_order', 'created_at', 'updated_at'],
    'work_order_task_files': ['id', 'work_order_task_id', 'file_id'],
    'work_order_tasks': ['id', 'work_order_id', 'title', 'description', 'assigned_to', 'status', 'created_at', 'completed_at', 'task_group_id', 'task_type', 'sort_order', 'completed_by', 'estimated_hours', 'actual_hours'],
    'work_order_users': ['id', 'work_order_id', 'user_id', 'hours_spent'],
    'work_orders': ['id', 'work_order_id', 'organization_id', 'asset_id', 'asset', 'location_id', 'location', 'site_id', 'title', 'description', 'issue_description', 'task_description', 'problem', 'solution', 'priority', 'status', 'work_order_type', 'maintenance_type', 'source', 'source_reference', 'external_wo_id', 'assigned_technician', 'assigned_vendor', 'vendor', 'scheduled_date', 'scheduled_time', 'estimated_hours', 'actual_hours', 'cost_parts_aed', 'cost_vendor_aed', 'requester_name', 'requester_email', 'requested_by_id', 'approval_type', 'criticality', 'safety', 'compliance', 'asset_intelligence', 'spare_parts', 'parts_order_status', 'suggested_vendors', 'resource_allocation', 'schedule_constraints', 'journey_log_id', 'cmms_work_order_id', 'created_at', 'updated_at', 'created_by', 'approved_at', 'completed_at', 'request_type', 'requester_phone', 'manpower', 'inspection_required', 'special_requirements', 'estimated_duration', 'prepared_at', 'sent_to_cmms_at', 'estimated_cost', 'asset_category'],
}

# table-name synonym (normalized) -> real plenum_cafm table
TABLE_ALIASES = {
    'account': 'accounts',
    'asset': 'assets',
    'asset_business': 'asset_businesses',
    'asset_category': 'asset_categories',
    'asset_document': 'asset_documents',
    'asset_event': 'asset_events',
    'asset_event_type': 'asset_event_types',
    'asset_reading': 'asset_readings',
    'asset_user': 'asset_users',
    'asset_warranty': 'asset_warranties',
    'assetbusinesses': 'asset_businesses',
    'assetcategories': 'asset_categories',
    'assetdocuments': 'asset_documents',
    'assetevents': 'asset_events',
    'asseteventtypes': 'asset_event_types',
    'assetofflinelog': 'asset_offline_log',
    'assetreadings': 'asset_readings',
    'assetusers': 'asset_users',
    'assetwarranties': 'asset_warranties',
    'billing_term': 'billing_terms',
    'billingterms': 'billing_terms',
    'bom_group': 'bom_groups',
    'bom_group_part': 'bom_group_parts',
    'bomgroupparts': 'bom_group_parts',
    'bomgroups': 'bom_groups',
    'business_classification': 'business_classifications',
    'business_group': 'business_groups',
    'businessclassifications': 'business_classifications',
    'businessgroups': 'business_groups',
    'certificate': 'certificates',
    'charge_department': 'charge_departments',
    'chargedepartments': 'charge_departments',
    'country': 'countries',
    'currency': 'currencies',
    'cycle_count': 'cycle_counts',
    'cyclecounts': 'cycle_counts',
    'file': 'files',
    'inspection': 'inspections',
    'inventory_transaction': 'inventory_transactions',
    'inventorytransactions': 'inventory_transactions',
    'known_issue': 'known_issues',
    'knownissues': 'known_issues',
    'location': 'locations',
    'maintenance_plan': 'maintenance_plans',
    'maintenance_type': 'maintenance_types',
    'maintenancehistory': 'maintenance_history',
    'maintenanceplans': 'maintenance_plans',
    'maintenancetypes': 'maintenance_types',
    'meter_reading_unit': 'meter_reading_units',
    'meterreadingunits': 'meter_reading_units',
    'misc_cost': 'misc_costs',
    'misc_cost_type': 'misc_cost_types',
    'misccosts': 'misc_costs',
    'misccosttypes': 'misc_cost_types',
    'move': 'moves',
    'move_asset': 'move_assets',
    'move_back': 'move_backs',
    'move_back_asset': 'move_back_assets',
    'move_status': 'move_statuses',
    'moveassets': 'move_assets',
    'movebackassets': 'move_back_assets',
    'movebacks': 'move_backs',
    'movestatuses': 'move_statuses',
    'notification': 'notifications',
    'organization': 'organizations',
    'permission': 'permissions',
    'ppm_schedule': 'ppm_schedules',
    'ppmschedules': 'ppm_schedules',
    'priority': 'priorities',
    'project': 'projects',
    'purchase_order': 'purchase_orders',
    'purchase_order_additional_cost': 'purchase_order_additional_costs',
    'purchase_order_additional_cost_type': 'purchase_order_additional_cost_types',
    'purchase_order_line_item': 'purchase_order_line_items',
    'purchase_order_log': 'purchase_order_logs',
    'purchase_order_status': 'purchase_order_statuses',
    'purchaseorderadditionalcosts': 'purchase_order_additional_costs',
    'purchaseorderadditionalcosttypes': 'purchase_order_additional_cost_types',
    'purchaseorderlineitems': 'purchase_order_line_items',
    'purchaseorderlogs': 'purchase_order_logs',
    'purchaseorders': 'purchase_orders',
    'purchaseorderstatuses': 'purchase_order_statuses',
    'rca_action': 'rca_actions',
    'rca_caus': 'rca_causes',
    'rca_grouping': 'rca_groupings',
    'rca_grouping_action': 'rca_grouping_actions',
    'rca_grouping_caus': 'rca_grouping_causes',
    'rca_problem': 'rca_problems',
    'rcaactions': 'rca_actions',
    'rcacauses': 'rca_causes',
    'rcagroupingactions': 'rca_grouping_actions',
    'rcagroupingcauses': 'rca_grouping_causes',
    'rcagroupings': 'rca_groupings',
    'rcaproblems': 'rca_problems',
    'reasonsassetoffline': 'reasons_asset_offline',
    'reasonsassetonline': 'reasons_asset_online',
    'receipt': 'receipts',
    'receipt_line_item': 'receipt_line_items',
    'receipt_status': 'receipt_statuses',
    'receiptlineitems': 'receipt_line_items',
    'receiptstatuses': 'receipt_statuses',
    'rfq': 'rfqs',
    'rfq_line_item': 'rfq_line_items',
    'rfq_status': 'rfq_statuses',
    'rfqlineitems': 'rfq_line_items',
    'rfqstatuses': 'rfq_statuses',
    'role': 'roles',
    'role_permission': 'role_permissions',
    'rolepermissions': 'role_permissions',
    'saved_space': 'saved_spaces',
    'savedspaces': 'saved_spaces',
    'schedule_trigger': 'schedule_triggers',
    'scheduled_maintenance_asset': 'scheduled_maintenance_assets',
    'scheduled_maintenance_part': 'scheduled_maintenance_parts',
    'scheduled_maintenance_status': 'scheduled_maintenance_statuses',
    'scheduled_maintenance_user': 'scheduled_maintenance_users',
    'scheduled_task': 'scheduled_tasks',
    'scheduledmaintenanceassets': 'scheduled_maintenance_assets',
    'scheduledmaintenanceparts': 'scheduled_maintenance_parts',
    'scheduledmaintenancestatuses': 'scheduled_maintenance_statuses',
    'scheduledmaintenanceusers': 'scheduled_maintenance_users',
    'scheduledtasks': 'scheduled_tasks',
    'scheduletriggers': 'schedule_triggers',
    'site': 'sites',
    'site_user': 'site_users',
    'siteusers': 'site_users',
    'sla_policy': 'sla_policies',
    'slapolicies': 'sla_policies',
    'spare_part': 'spare_parts',
    'spareparts': 'spare_parts',
    'stock_cycle_count': 'stock_cycle_counts',
    'stock_tx_type': 'stock_tx_types',
    'stockcyclecounts': 'stock_cycle_counts',
    'stockhistory': 'stock_history',
    'stocktxtypes': 'stock_tx_types',
    'task_group': 'task_groups',
    'taskgroups': 'task_groups',
    'technician': 'technicians',
    'technician_skill': 'technician_skills',
    'technicianskills': 'technician_skills',
    'uploaded_file': 'uploaded_files',
    'uploadedfiles': 'uploaded_files',
    'user': 'users',
    'user_certification': 'user_certifications',
    'user_role': 'user_roles',
    'usercertifications': 'user_certifications',
    'userroles': 'user_roles',
    'vendor': 'vendors',
    'vendor_contact': 'vendor_contacts',
    'vendor_contract': 'vendor_contracts',
    'vendorcontacts': 'vendor_contacts',
    'vendorcontracts': 'vendor_contracts',
    'wo_approval_request': 'wo_approval_requests',
    'wo_approval_rule': 'wo_approval_rules',
    'wo_approval_suggestion': 'wo_approval_suggestions',
    'wo_approval_threshold': 'wo_approval_thresholds',
    'wo_asset': 'wo_assets',
    'wo_chat_session': 'wo_chat_sessions',
    'wo_journey_log': 'wo_journey_logs',
    'wo_location': 'wo_locations',
    'woapprovalrequests': 'wo_approval_requests',
    'woapprovalrules': 'wo_approval_rules',
    'woapprovalsuggestions': 'wo_approval_suggestions',
    'woapprovalthresholds': 'wo_approval_thresholds',
    'woapproverrouting': 'wo_approver_routing',
    'woassets': 'wo_assets',
    'wochatsessions': 'wo_chat_sessions',
    'wojourneylogs': 'wo_journey_logs',
    'wolocations': 'wo_locations',
    'work_order': 'work_orders',
    'work_order_asset': 'work_order_assets',
    'work_order_attachment': 'work_order_attachments',
    'work_order_business': 'work_order_businesses',
    'work_order_comment': 'work_order_comments',
    'work_order_part': 'work_order_parts',
    'work_order_status': 'work_order_statuses',
    'work_order_task': 'work_order_tasks',
    'work_order_task_file': 'work_order_task_files',
    'work_order_user': 'work_order_users',
    'workorderassets': 'work_order_assets',
    'workorderattachments': 'work_order_attachments',
    'workorderbusinesses': 'work_order_businesses',
    'workordercomments': 'work_order_comments',
    'workorderhistory': 'work_order_history',
    'workorderparts': 'work_order_parts',
    'workorders': 'work_orders',
    'workorderstatuses': 'work_order_statuses',
    'workordertaskfiles': 'work_order_task_files',
    'workordertasks': 'work_order_tasks',
    'workorderusers': 'work_order_users',
    'wostatushistory': 'wo_status_history',
}

# table -> {column alias (normalized) -> real column}
COLUMN_ALIASES_BY_TABLE = {
    'accounts': {'account_dblmeterreading': 'dblmeterreading', 'account_dblsubtotal': 'dblsubtotal', 'account_dbltotalcost': 'dbltotalcost', 'account_dtmdate': 'dtmdate', 'account_dtmdatesubmitted': 'dtmdatesubmitted', 'account_intassignedtouserid': 'intassignedtouserid', 'account_intbomcontrolid': 'intbomcontrolid', 'account_intbompartcontrolid': 'intbompartcontrolid', 'account_intbusinessid': 'intbusinessid', 'account_intbusinessroletypeid': 'intbusinessroletypeid', 'account_intcode': 'intcode', 'account_intconsumesassetid': 'intconsumesassetid', 'account_intcountryid': 'intcountryid', 'account_intcyclecountid': 'intcyclecountid', 'account_intfileid': 'intfileid', 'account_intmovestatusid': 'intmovestatusid', 'account_intparentid': 'intparentid', 'account_intprojectid': 'intprojectid', 'account_intpurchaseorderlineitemid': 'intpurchaseorderlineitemid', 'account_intpurchaseorderstatusid': 'intpurchaseorderstatusid', 'account_intreceiptid': 'intreceiptid', 'account_intreceiptstatusid': 'intreceiptstatusid', 'account_intregionid': 'intregionid', 'account_intrequestedbyuserid': 'intrequestedbyuserid', 'account_intsiteid': 'intsiteid', 'account_intsize': 'intsize', 'account_intstockid': 'intstockid', 'account_intsubmittedbyuserid': 'intsubmittedbyuserid', 'account_intupdated': 'intupdated', 'account_intuserid': 'intuserid', 'account_intworkorderstatusid': 'intworkorderstatusid', 'account_straddress': 'straddress', 'account_strassetids': 'strassetids', 'account_strassets': 'strassets', 'account_strassigneduserids': 'strassigneduserids', 'account_strassignedusers': 'strassignedusers', 'account_strcity': 'strcity', 'account_strcode': 'strcode', 'account_strcompletionnotes': 'strcompletionnotes', 'account_strcontents': 'strcontents', 'account_strdescription': 'strdescription', 'account_streventcode': 'streventcode', 'account_strfax': 'strfax', 'account_strlink': 'strlink', 'account_strname': 'strname', 'account_strnotes': 'strnotes', 'account_strpostalcode': 'strpostalcode', 'account_strproblem': 'strproblem', 'account_strprovince': 'strprovince', 'account_strsolution': 'strsolution', 'account_strwebsite': 'strwebsite', 'desc': 'description', 'org_id': 'organization_id'},
    'asset_categories': {'cat_name': 'category_name', 'org_id': 'organization_id', 'parent_cat_id': 'parent_category_id'},
    'asset_event_types': {'org_id': 'organization_id'},
    'asset_events': {'desc': 'description'},
    'asset_readings': {'asset_reading_unit': 'unit', 'asset_reading_value': 'value', 'org_id': 'organization_id'},
    'asset_warranties': {'asset_warranty_provider': 'provider', 'desc': 'description'},
    'assets': {'asset_aisle': 'aisle', 'asset_barcode': 'barcode', 'asset_criticality': 'criticality', 'asset_location': 'location', 'asset_make': 'make', 'asset_manufacturer': 'manufacturer', 'asset_model': 'model', 'asset_row': 'row', 'asset_timezone': 'timezone', 'bin_no': 'bin_number', 'cat': 'category', 'cat_id': 'category_id', 'charge_dept_id': 'charge_department_id', 'loc': 'location', 'loc_code': 'location_code', 'loc_id': 'location_id', 'mfg': 'manufacturer', 'model_no': 'model_number', 'org_id': 'organization_id', 'serial': 'serial_number', 'serial_no': 'serial_number', 'sn': 'serial_number', 'stock_loc': 'stock_location'},
    'billing_terms': {'org_id': 'organization_id'},
    'bom_group_parts': {'bom_group_part_quantity': 'quantity', 'qty': 'quantity'},
    'bom_groups': {'desc': 'description', 'org_id': 'organization_id'},
    'business_classifications': {'org_id': 'organization_id'},
    'business_groups': {'org_id': 'organization_id'},
    'charge_departments': {'desc': 'description', 'org_id': 'organization_id'},
    'currencies': {'currency_symbol': 'symbol'},
    'cycle_counts': {'org_id': 'organization_id'},
    'files': {'org_id': 'organization_id', 'size_bytes': 'file_size_bytes'},
    'inspections': {'date': 'inspection_date', 'inspection_inspector': 'inspector', 'inspection_observations': 'observations'},
    'inventory_transactions': {'inventory_transaction_quantity': 'quantity', 'qty': 'quantity', 'ref_id': 'reference_id', 'ref_type': 'reference_type'},
    'known_issues': {'issue_desc': 'issue_description', 'known_issue_manufacturer': 'manufacturer', 'known_issue_model': 'model', 'known_issue_solutions': 'solutions', 'mfg': 'manufacturer'},
    'locations': {'addr': 'address', 'location_address': 'address', 'location_city': 'city', 'location_country': 'country', 'location_level': 'level', 'location_province': 'province', 'location_timezone': 'timezone', 'org_id': 'organization_id', 'parent_loc_id': 'parent_location_id'},
    'maintenance_plans': {'charge_dept_id': 'charge_department_id', 'desc': 'description', 'org_id': 'organization_id'},
    'maintenance_types': {'desc': 'description', 'org_id': 'organization_id'},
    'meter_reading_units': {'meter_reading_unit_precision': 'precision', 'meter_reading_unit_symbol': 'symbol', 'org_id': 'organization_id'},
    'misc_cost_types': {'org_id': 'organization_id'},
    'misc_costs': {'amt': 'amount', 'desc': 'description', 'misc_cost_amount': 'amount', 'type_id': 'misc_cost_type_id'},
    'move_backs': {'org_id': 'organization_id'},
    'move_statuses': {'org_id': 'organization_id'},
    'moves': {'org_id': 'organization_id'},
    'notifications': {'notification_message': 'message', 'notification_title': 'title', 'org_id': 'organization_id'},
    'organizations': {'addr': 'address', 'organization_address': 'address', 'organization_country': 'country', 'organization_industry': 'industry', 'organization_timezone': 'timezone'},
    'permissions': {'desc': 'description'},
    'ppm_schedules': {'loc': 'location', 'ppm_schedule_active': 'active', 'ppm_schedule_frequency': 'frequency', 'ppm_schedule_location': 'location', 'ppm_schedule_priority': 'priority', 'task_desc': 'task_description'},
    'priorities': {'org_id': 'organization_id'},
    'projects': {'desc': 'description', 'org_id': 'organization_id'},
    'purchase_order_additional_cost_types': {'org_id': 'organization_id'},
    'purchase_order_additional_costs': {'amt': 'amount', 'desc': 'description', 'purchase_order_additional_cost_amount': 'amount'},
    'purchase_order_line_items': {'desc': 'description', 'purchase_order_line_item_quantity': 'quantity', 'qty': 'quantity'},
    'purchase_order_logs': {'purchase_order_log_action': 'action'},
    'purchase_order_statuses': {'org_id': 'organization_id'},
    'purchase_orders': {'charge_dept_id': 'charge_department_id', 'org_id': 'organization_id', 'purchase_order_subtotal': 'subtotal', 'tax_amt': 'tax_amount', 'total_amt': 'total_amount'},
    'rca_actions': {'desc': 'description', 'org_id': 'organization_id'},
    'rca_causes': {'desc': 'description', 'org_id': 'organization_id'},
    'rca_problems': {'desc': 'description', 'org_id': 'organization_id'},
    'reasons_asset_offline': {'desc': 'description', 'org_id': 'organization_id'},
    'reasons_asset_online': {'desc': 'description', 'org_id': 'organization_id'},
    'receipt_line_items': {'qty_ordered': 'quantity_ordered', 'qty_received': 'quantity_received'},
    'receipt_statuses': {'org_id': 'organization_id'},
    'rfq_line_items': {'desc': 'description', 'qty': 'quantity', 'rfq_line_item_quantity': 'quantity'},
    'rfq_statuses': {'org_id': 'organization_id'},
    'rfqs': {'org_id': 'organization_id'},
    'roles': {'desc': 'description', 'org_id': 'organization_id'},
    'saved_spaces': {'org_id': 'organization_id', 'saved_space_kind': 'kind'},
    'scheduled_maintenance_parts': {'qty_required': 'quantity_required'},
    'scheduled_maintenance_statuses': {'org_id': 'organization_id'},
    'scheduled_tasks': {'desc': 'description'},
    'sites': {'org_id': 'organization_id', 'site_city': 'city', 'site_country': 'country', 'site_floors': 'floors', 'site_timezone': 'timezone'},
    'sla_policies': {'org_id': 'organization_id', 'sla_policy_priority': 'priority'},
    'spare_parts': {'desc': 'description', 'max_qty': 'max_quantity', 'maximum_quantity': 'max_quantity', 'org_id': 'organization_id', 'stock_qty': 'stock_quantity'},
    'stock_cycle_counts': {'quantity_counted': 'qty_counted', 'quantity_expected': 'qty_expected', 'stock_cycle_count_variance': 'variance'},
    'stock_history': {'desc': 'description', 'quantity_after': 'qty_after', 'quantity_change': 'qty_change'},
    'stock_tx_types': {'affects_quantity': 'affects_qty', 'org_id': 'organization_id'},
    'task_groups': {'desc': 'description', 'org_id': 'organization_id'},
    'technicians': {'base_loc': 'base_location', 'org_id': 'organization_id'},
    'transportation': {'org_id': 'organization_id', 'transportation_month': 'month', 'transportation_priority': 'priority', 'transportation_remarks': 'remarks', 'transportation_specialization': 'specialization', 'work_order_reference': 'work_order_ref'},
    'user_certifications': {'desc': 'description'},
    'users': {'org_id': 'organization_id', 'ph': 'phone', 'user_email': 'email', 'user_phone': 'phone', 'user_phone2': 'phone2', 'user_role': 'role'},
    'vendor_contacts': {'ph': 'phone', 'vendor_contact_designation': 'designation', 'vendor_contact_email': 'email', 'vendor_contact_phone': 'phone'},
    'vendor_contracts': {'org_id': 'organization_id'},
    'vendors': {'addr': 'address', 'org_id': 'organization_id', 'ph': 'phone', 'vendor_address': 'address', 'vendor_city': 'city', 'vendor_country': 'country', 'vendor_email': 'email', 'vendor_fax': 'fax', 'vendor_phone': 'phone', 'vendor_province': 'province', 'vendor_website': 'website'},
    'wo_approval_requests': {'wo_approval_request_approver': 'approver', 'wo_approval_request_level': 'level'},
    'wo_approval_rules': {'wo_approval_rule_active': 'active', 'wo_approval_rule_dimension': 'dimension', 'wo_approval_rule_weight': 'weight'},
    'wo_approval_suggestions': {'wo_approval_suggestion_accepted': 'accepted', 'wo_approval_suggestion_confidence': 'confidence', 'wo_approval_suggestion_fingerprint': 'fingerprint', 'wo_approval_suggestion_source': 'source'},
    'wo_approval_thresholds': {'maximum_score': 'max_score', 'minimum_score': 'min_score', 'wo_approval_threshold_level': 'level'},
    'wo_approver_routing': {'asset_cat': 'asset_category', 'wo_approver_routing_active': 'active'},
    'wo_assets': {'loc': 'location', 'mfg': 'manufacturer', 'serial': 'serial_number', 'serial_no': 'serial_number', 'sn': 'serial_number', 'wo_asset_active': 'active', 'wo_asset_location': 'location', 'wo_asset_manufacturer': 'manufacturer', 'wo_asset_model': 'model'},
    'wo_chat_sessions': {'wo_chat_session_context': 'context', 'wo_chat_session_messages': 'messages', 'wo_chat_session_source': 'source'},
    'wo_journey_logs': {'wo_journey_log_completed': 'completed', 'wo_journey_log_deviations': 'deviations', 'wo_journey_log_events': 'events', 'wo_journey_log_milestones': 'milestones'},
    'wo_locations': {'loc_id': 'location_id', 'wo_location_active': 'active', 'wo_location_building': 'building', 'wo_location_floor': 'floor', 'wo_location_zone': 'zone'},
    'work_order_comments': {'work_order_comment_comment': 'comment'},
    'work_order_parts': {'qty_used': 'quantity_used'},
    'work_order_statuses': {'org_id': 'organization_id'},
    'work_order_tasks': {'desc': 'description', 'work_order_task_title': 'title'},
    'work_orders': {'asset_cat': 'asset_category', 'desc': 'description', 'issue_desc': 'issue_description', 'loc': 'location', 'loc_id': 'location_id', 'org_id': 'organization_id', 'requester_ph': 'requester_phone', 'source_ref': 'source_reference', 'task_desc': 'task_description', 'work_order_asset': 'asset', 'work_order_compliance': 'compliance', 'work_order_criticality': 'criticality', 'work_order_location': 'location', 'work_order_manpower': 'manpower', 'work_order_priority': 'priority', 'work_order_problem': 'problem', 'work_order_safety': 'safety', 'work_order_solution': 'solution', 'work_order_source': 'source', 'work_order_title': 'title', 'work_order_vendor': 'vendor'},
}

# table -> primary-key column (derived from null/default schema metadata)
PRIMARY_KEYS = {
    'accounts': 'id',
    'asset_businesses': 'id',
    'asset_categories': 'id',
    'asset_documents': 'id',
    'asset_event_types': 'id',
    'asset_events': 'id',
    'asset_offline_log': 'id',
    'asset_readings': 'id',
    'asset_users': 'id',
    'asset_warranties': 'id',
    'assets': 'id',
    'billing_terms': 'id',
    'bom_group_parts': 'id',
    'bom_groups': 'id',
    'business_classifications': 'id',
    'business_groups': 'id',
    'certificates': 'certificate_id',
    'charge_departments': 'id',
    'countries': 'id',
    'currencies': 'id',
    'cycle_counts': 'id',
    'files': 'id',
    'inspections': 'id',
    'inventory_transactions': 'id',
    'known_issues': 'id',
    'locations': 'id',
    'maintenance_history': 'id',
    'maintenance_plans': 'id',
    'maintenance_types': 'id',
    'meter_reading_units': 'id',
    'misc_cost_types': 'id',
    'misc_costs': 'id',
    'move_assets': 'id',
    'move_back_assets': 'id',
    'move_backs': 'id',
    'move_statuses': 'id',
    'moves': 'id',
    'notifications': 'id',
    'organizations': 'id',
    'permissions': 'id',
    'ppm_schedules': 'schedule_id',
    'priorities': 'id',
    'projects': 'id',
    'purchase_order_additional_cost_types': 'id',
    'purchase_order_additional_costs': 'id',
    'purchase_order_line_items': 'id',
    'purchase_order_logs': 'id',
    'purchase_order_statuses': 'id',
    'purchase_orders': 'id',
    'rca_actions': 'id',
    'rca_causes': 'id',
    'rca_grouping_actions': 'id',
    'rca_grouping_causes': 'id',
    'rca_groupings': 'id',
    'rca_problems': 'id',
    'reasons_asset_offline': 'id',
    'reasons_asset_online': 'id',
    'receipt_line_items': 'id',
    'receipt_statuses': 'id',
    'receipts': 'id',
    'rfq_line_items': 'id',
    'rfq_statuses': 'id',
    'rfqs': 'id',
    'role_permissions': 'id',
    'roles': 'id',
    'saved_spaces': 'id',
    'schedule_triggers': 'id',
    'scheduled_maintenance_assets': 'id',
    'scheduled_maintenance_parts': 'id',
    'scheduled_maintenance_statuses': 'id',
    'scheduled_maintenance_users': 'id',
    'scheduled_tasks': 'id',
    'site_users': 'id',
    'sites': 'site_id',
    'sla_policies': 'id',
    'spare_parts': 'id',
    'stock_cycle_counts': 'id',
    'stock_history': 'id',
    'stock_tx_types': 'id',
    'task_groups': 'id',
    'technician_skills': 'id',
    'technicians': 'id',
    'transportation': 'id',
    'uploaded_files': 'id',
    'user_certifications': 'id',
    'user_roles': 'id',
    'users': 'id',
    'vendor_contacts': 'id',
    'vendor_contracts': 'id',
    'vendors': 'id',
    'wo_approval_requests': 'request_id',
    'wo_approval_rules': 'rule_id',
    'wo_approval_suggestions': 'suggestion_id',
    'wo_approval_thresholds': 'level',
    'wo_approver_routing': 'id',
    'wo_assets': 'asset_id',
    'wo_chat_sessions': 'session_id',
    'wo_journey_logs': 'id',
    'wo_locations': 'location_id',
    'wo_status_history': 'history_id',
    'work_order_assets': 'id',
    'work_order_attachments': 'id',
    'work_order_businesses': 'id',
    'work_order_comments': 'id',
    'work_order_history': 'id',
    'work_order_parts': 'id',
    'work_order_statuses': 'id',
    'work_order_task_files': 'id',
    'work_order_tasks': 'id',
    'work_order_users': 'id',
    'work_orders': 'id',
}
